services:
  backup-mongodb-s3:
    image: registry.uni-kassel.dev/backup/mongodb-s3
    build:
      tags:
        - registry.uni-kassel.dev/backup/mongodb-s3
        - registry.uni-kassel.dev/backup/mongodb-s3:v2
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
